### ISSUE TITLE
Saving single term of spherical harmonic acceleration causes runtime error

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudatpy#26] opened 2021-11-30 10:46 UTC
If the third argument of [this function](https://tudatpy.readthedocs.io/en/latest/dependent_variable.html#tudatpy.numerical_simulation.propagation_setup.dependent_variable.spherical_harmonic_terms_acceleration_norm) is called with a list of only one tuple, the program crashes.

*Example*
✅ the following works:
`propagation_setup.dependent_variable.spherical_harmonic_terms_acceleration_norm( "Spacecraft", "Earth", [(0, 0), (2, 0)])`
❌ the following causes an error:
`propagation_setup.dependent_variable.spherical_harmonic_terms_acceleration_norm( "Spacecraft", "Earth", [(0, 0)])`.

Probably due to a pybind conversion from Python list to C++ std::vector?

**Comment by DominicDirkx** [comment] 2022-03-19 12:25
> Probably due to a pybind conversion from Python list to C++ std::vector?

I finally decided to have a look a this: the issue is not in pybind, but in Tudat. In this case, the dependent variable is a scalar, but in the general case it will be a vector, leading to this being incorrectly processed. I've made a modification to the code that should correct it. Tests are now building.

**Comment by gaffarelj** [comment] 2022-03-20 16:55
I assume that these tests passed, and that we can now close this issue @DominicDirkx ?

**Closed** 2022-03-21 07:54 UTC
Labels: bug
